from app.models import db, EECBGActivity, environment, SCHEMA
from sqlalchemy.sql import text

def seed_eecbg_activities():
    activities = [
        {
            "user_id": 1,
            "form_id": 1,
            "category_1_strategy_development": True,
            "category_2_retaining_consulting": True,
            "category_6_efficiency_programs": True,
            "category_8_building_codes": True,
            "category_11_landfill_gas": True,
            "category_10_material_conservation": True,
            "category_14_private_sector_funding": True,
            "category_13_renewable_energy": True,
            "category_12_traffic_signals": True,
        },
        {
            "user_id": 2,
            "form_id": 2,
            "category_1_strategy_development": True,
            "category_2_retaining_consulting": True,
        },
        {
            "user_id": 3,
            "form_id": 3,
            "category_1_strategy_development": True,
            "category_2_retaining_consulting": True,
            "category_3_residential_audits": True,
            "category_4_financial_incentives": True,
            "category_5_retrofit_grants": True,
            "category_6_efficiency_programs": True,
            "category_7_transportation_energy": True,
            "category_8_building_codes": True,
            "category_9_energy_distribution": True,
            "category_10_material_conservation": True,
            "category_11_landfill_gas": True,
            "category_13_renewable_energy": True,
            "category_14_private_sector_funding": True,
        },
        {
            "user_id": 4,
            "form_id": 4,
            "category_1_strategy_development": True,
            "category_4_financial_incentives": True,
            "category_6_efficiency_programs": True,
            "category_9_energy_distribution": True,
            "category_2_retaining_consulting": True,
            "category_5_retrofit_grants": True,
        },
        {
            "user_id": 5,
            "form_id": 5,
            "category_1_strategy_development": True,
            "category_2_retaining_consulting": True,
            "category_6_efficiency_programs": True,
            "category_3_residential_audits": True,
            "category_11_landfill_gas": True,
        },
        {
            "user_id": 6,
            "form_id": 6,
            "category_14_private_sector_funding": True,
        },
        {
            "user_id": 7,
            "form_id": 7,
            "category_1_strategy_development": True,
            "category_2_retaining_consulting": True,
            "category_7_transportation_energy": True,
            "category_9_energy_distribution": True,
            "category_13_renewable_energy": True,
            "category_14_private_sector_funding": True,
        },
        {
            "user_id": 8,
            "form_id": 8,
            "category_1_strategy_development": True,
            "category_2_retaining_consulting": True,
            "category_6_efficiency_programs": True,
            "category_7_transportation_energy": True,
            "category_8_building_codes": True,
            "category_10_material_conservation": True,
            "category_11_landfill_gas": True,
            "category_12_traffic_signals": True,
            "category_14_private_sector_funding": True,
        },
        {
            "user_id": 9,
            "form_id": 9,
            "category_1_strategy_development": True,
            "category_6_efficiency_programs": True,
            "category_7_transportation_energy": True,
            "category_9_energy_distribution": True,
            "category_12_traffic_signals": True,
            "category_13_renewable_energy": True,
            "category_14_private_sector_funding": True,
        },
        {
            "user_id": 10,
            "form_id": 10,
            "category_1_strategy_development": True,
            "category_3_residential_audits": True,
            "category_4_financial_incentives": True,
            "category_6_efficiency_programs": True,
            "category_8_building_codes": True,
            "category_9_energy_distribution": True,
            "category_13_renewable_energy": True,
            "category_14_private_sector_funding": True,
        },
        {
            "user_id": 11,
            "form_id": 11,
            "category_1_strategy_development": True,
            "category_2_retaining_consulting": True,
            "category_3_residential_audits": True,
            "category_4_financial_incentives": True,
            "category_5_retrofit_grants": True,
            "category_6_efficiency_programs": True,
            "category_11_landfill_gas": True,
            "category_14_private_sector_funding": True,
        },
        {
            "user_id": 12,
            "form_id": 12,
            "category_1_strategy_development": True,
            "category_2_retaining_consulting": True,
            "category_8_building_codes": True,
            "category_13_renewable_energy": True,
            "category_14_private_sector_funding": True,
        },
        {
            "user_id": 13,
            "form_id": 13,
            "category_9_energy_distribution": True,
            "category_2_retaining_consulting": True,
        },
        {
            "user_id": 14,
            "form_id": 14,
            "category_1_strategy_development": True,
            "category_2_retaining_consulting": True,
            "category_3_residential_audits": True,
            "category_5_retrofit_grants": True,
            "category_6_efficiency_programs": True,
            "category_9_energy_distribution": True,
            "category_13_renewable_energy": True,
        },
        {
            "user_id": 15,
            "form_id": 15,
            "category_1_strategy_development": True,
            "category_2_retaining_consulting": True,
            "category_4_financial_incentives": True,
            "category_6_efficiency_programs": True,
            "category_8_building_codes": True,
            "category_9_energy_distribution": True,
            "category_10_material_conservation": True,
            "category_12_traffic_signals": True,
            "category_13_renewable_energy": True,
            "category_14_private_sector_funding": True,
        },
        {
            "user_id": 16,
            "form_id": 16,
            "category_1_strategy_development": True,
            "category_2_retaining_consulting": True,
            "category_13_renewable_energy": True,
            "category_14_private_sector_funding": True,
        },
        {
            "user_id": 17,
            "form_id": 17,
            "category_3_residential_audits": True,
            "category_6_efficiency_programs": True,
            "category_8_building_codes": True,
        },
        {
            "user_id": 18,
            "form_id": 18,
            "category_6_efficiency_programs": True,
        },
        {
            "user_id": 19,
            "form_id": 19,
            "category_1_strategy_development": True,
            "category_2_retaining_consulting": True,
            "category_5_retrofit_grants": True,
            "category_9_energy_distribution": True,
            "category_13_renewable_energy": True,
        },
        {
            "user_id": 20,
            "form_id": 20,
            "category_1_strategy_development": True,
            "category_13_renewable_energy": True,
            "category_14_private_sector_funding": True,
        },
        {
            "user_id": 21,
            "form_id": 21,
            "category_1_strategy_development": True,
            "category_2_retaining_consulting": True,
            "category_3_residential_audits": True,
            "category_6_efficiency_programs": True,
            "category_7_transportation_energy": True,
            "category_14_private_sector_funding": True,
        },
        {
            "user_id": 22,
            "form_id": 22,
            "category_2_retaining_consulting": True,
            "category_9_energy_distribution": True,
            "category_13_renewable_energy": True,
        },
        {
            "user_id": 23,
            "form_id": 23,
            "category_1_strategy_development": True,
        },
        {
            "user_id": 24,
            "form_id": 24,
            "category_1_strategy_development": True,
            "category_5_retrofit_grants": True,
            "category_6_efficiency_programs": True,
            "category_9_energy_distribution": True,
            "category_11_landfill_gas": True,
            "category_13_renewable_energy": True,
            "category_14_private_sector_funding": True,
        },
        {
            "user_id": 25,
            "form_id": 25,
            "category_1_strategy_development": True,
            "category_5_retrofit_grants": True,
            "category_13_renewable_energy": True,
        },
        {
            "user_id": 26,
            "form_id": 26,
            "category_1_strategy_development": True,
            "category_6_efficiency_programs": True,
            "category_9_energy_distribution": True,
        },
        {
            "user_id": 27,
            "form_id": 27,
            "category_1_strategy_development": True,
            "category_2_retaining_consulting": True,
            "category_3_residential_audits": True,
            "category_4_financial_incentives": True,
            "category_5_retrofit_grants": True,
            "category_6_efficiency_programs": True,
            "category_9_energy_distribution": True,
            "category_13_renewable_energy": True,
            "category_14_private_sector_funding": True,
        },
        {
            "user_id": 28,
            "form_id": 28,
            "category_1_strategy_development": True,
            "category_3_residential_audits": True,
            "category_4_financial_incentives": True,
            "category_6_efficiency_programs": True,
            "category_9_energy_distribution": True,
        },
        {
            "user_id": 29,
            "form_id": 29,
            "category_1_strategy_development": True,
            "category_4_financial_incentives": True,
            "category_5_retrofit_grants": True,
            "category_7_transportation_energy": True,
            "category_10_material_conservation": True,
            "category_13_renewable_energy": True,
            "category_14_private_sector_funding": True,
        },
        {
            "user_id": 30,
            "form_id": 30,
            "category_1_strategy_development": True,
            "category_2_retaining_consulting": True,
            "category_3_residential_audits": True,
        },
        {
            "user_id": 31,
            "form_id": 31,
            "category_1_strategy_development": True,
            "category_2_retaining_consulting": True,
            "category_4_financial_incentives": True,
            "category_5_retrofit_grants": True,
            "category_9_energy_distribution": True,
            "category_14_private_sector_funding": True,
        },
        {
            "user_id": 32,
            "form_id": 32,
            "category_1_strategy_development": True,
            "category_3_residential_audits": True,
            "category_4_financial_incentives": True,
        },
        {
            "user_id": 33,
            "form_id": 33,
            "category_1_strategy_development": True,
            "category_2_retaining_consulting": True,
            "category_3_residential_audits": True,
            "category_4_financial_incentives": True,
            "category_5_retrofit_grants": True,
            "category_6_efficiency_programs": True,
            "category_10_material_conservation": True,
            "category_11_landfill_gas": True,
            "category_13_renewable_energy": True,
            "category_14_private_sector_funding": True,
        },
        {
            "user_id": 34,
            "form_id": 34,
            "category_1_strategy_development": True,
            "category_2_retaining_consulting": True,
            "category_9_energy_distribution": True,
        },
        {
            "user_id": 35,
            "form_id": 35,
            "category_1_strategy_development": True,
            "category_5_retrofit_grants": True,
            "category_6_efficiency_programs": True,
            "category_7_transportation_energy": True,
            "category_9_energy_distribution": True,
            "category_14_private_sector_funding": True,
        },
        {
            "user_id": 36,
            "form_id": 36,
            "category_1_strategy_development": True,
            "category_2_retaining_consulting": True,
            "category_7_transportation_energy": True,
            "category_14_private_sector_funding": True,
        },
        {
            "user_id": 37,
            "form_id": 37,
            "category_1_strategy_development": True,
            "category_9_energy_distribution": True,
        },
        {
            "user_id": 38,
            "form_id": 38,
            "category_2_retaining_consulting": True,
            "category_9_energy_distribution": True,
        },
        {
            "user_id": 39,
            "form_id": 39,
            "category_1_strategy_development": True,
            "category_6_efficiency_programs": True,
            "category_7_transportation_energy": True,
            "category_9_energy_distribution": True,
            "category_11_landfill_gas": True,
            "category_12_traffic_signals": True,
            "category_13_renewable_energy": True,
            "category_14_private_sector_funding": True,
        },
        {
            "user_id": 40,
            "form_id": 40,
            "category_1_strategy_development": True,
            "category_2_retaining_consulting": True,
        },
        {
            "user_id": 41,
            "form_id": 41,
            "category_8_building_codes": True,
        },
        {
            "user_id": 42,
            "form_id": 42,
            "category_1_strategy_development": True,
            "category_4_financial_incentives": True,
            "category_5_retrofit_grants": True,
            "category_6_efficiency_programs": True,
            "category_7_transportation_energy": True,
            "category_10_material_conservation": True,
            "category_11_landfill_gas": True,
            "category_13_renewable_energy": True,
            "category_14_private_sector_funding": True,
        },
        {
            "user_id": 43,
            "form_id": 43,
            "category_2_retaining_consulting": True,
            "category_3_residential_audits": True,
            "category_4_financial_incentives": True,
            "category_5_retrofit_grants": True,
            "category_6_efficiency_programs": True,
            "category_8_building_codes": True,
            "category_13_renewable_energy": True,
        },
        {
            "user_id": 44,
            "form_id": 44,
            "category_1_strategy_development": True,
            "category_4_financial_incentives": True,
            "category_5_retrofit_grants": True,
            "category_6_efficiency_programs": True,
            "category_9_energy_distribution": True,
            "category_13_renewable_energy": True,
            "category_14_private_sector_funding": True,
        },
        {
            "user_id": 45,
            "form_id": 45,
            "category_1_strategy_development": True,
            "category_2_retaining_consulting": True,
            "category_5_retrofit_grants": True,
            "category_6_efficiency_programs": True,
        },
        {
            "user_id": 46,
            "form_id": 46,
            "category_1_strategy_development": True,
            "category_2_retaining_consulting": True,
            "category_4_financial_incentives": True,
            "category_6_efficiency_programs": True,
            "category_7_transportation_energy": True,
            "category_9_energy_distribution": True,
            "category_14_private_sector_funding": True,
        },
        {
            "user_id": 47,
            "form_id": 47,
            "category_1_strategy_development": True,
            "category_2_retaining_consulting": True,
            "category_3_residential_audits": True,
            "category_4_financial_incentives": True,
            "category_5_retrofit_grants": True,
            "category_6_efficiency_programs": True,
            "category_12_traffic_signals": True,
            "category_13_renewable_energy": True,
            "category_14_private_sector_funding": True,
        },
        {
            "user_id": 48,
            "form_id": 48,
            "category_1_strategy_development": True,
            "category_5_retrofit_grants": True,
        },
        {
            "user_id": 49,
            "form_id": 49,
            "category_1_strategy_development": True,
            "category_3_residential_audits": True,
            "category_4_financial_incentives": True,
            "category_5_retrofit_grants": True,
            "category_6_efficiency_programs": True,
            "category_7_transportation_energy": True,
            "category_9_energy_distribution": True,
            "category_13_renewable_energy": True,
        },
        {
            "user_id": 50,
            "form_id": 50,
            "category_1_strategy_development": True,
            "category_2_retaining_consulting": True,
            "category_4_financial_incentives": True,
            "category_6_efficiency_programs": True,
            "category_7_transportation_energy": True,
            "category_9_energy_distribution": True,
            "category_10_material_conservation": True,
            "category_11_landfill_gas": True,
            "category_13_renewable_energy": True,
            "category_14_private_sector_funding": True,
        },
        {
            "user_id": 51,
            "form_id": 51,
            "category_2_retaining_consulting": True,
            "category_3_residential_audits": True,
            "category_6_efficiency_programs": True,
            "category_8_building_codes": True,
        },
        {
            "user_id": 52,
            "form_id": 52,
            "category_1_strategy_development": True,
            "category_2_retaining_consulting": True,
            "category_4_financial_incentives": True,
            "category_14_private_sector_funding": True,
        },
        {
            "user_id": 53,
            "form_id": 53,
            "category_6_efficiency_programs": True,
            "category_9_energy_distribution": True,
            "category_11_landfill_gas": True,
        },
        {
            "user_id": 54,
            "form_id": 54,
            "category_1_strategy_development": True,
            "category_2_retaining_consulting": True,
            "category_6_efficiency_programs": True,
            "category_7_transportation_energy": True,
            "category_9_energy_distribution": True,
            "category_10_material_conservation": True,
            "category_11_landfill_gas": True,
            "category_12_traffic_signals": True,
            "category_13_renewable_energy": True,
        },
        {
            "user_id": 55,
            "form_id": 55,
            "category_1_strategy_development": True,
            "category_3_residential_audits": True,
            "category_13_renewable_energy": True,
        },
        ]

    for activity in activities:
        db.session.add(EECBGActivity(**activity))

    db.session.commit()

def undo_eecbg_activities():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.eecbg_activities_10 RESTART IDENTITY CASCADE;")
    else:
        db.session.execute(text("DELETE FROM eecbg_activities_10"))
    db.session.commit()
