"""Updated models with new tables

Revision ID: 21869ebf788b
Revises: ffdc0a98111c
Create Date: 2025-01-22 13:58:28.766358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21869ebf788b'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_workPhone_3', sa.String(), nullable=True),
    sa.Column('organization_name_4', sa.String(), nullable=False),
    sa.Column('user_email_5', sa.String(), nullable=False),
    sa.Column('organization_website_6', sa.String(), nullable=True),
    sa.Column('user_jobTitle_7', sa.String(), nullable=True),
    sa.Column('user_mobilePhone_8', sa.String(), nullable=True),
    sa.Column('EECBGExperience_11', sa.String(), nullable=True),
    sa.Column('publicTaExperience_12', sa.String(), nullable=True),
    sa.Column('inPersonExperience_13', sa.String(), nullable=True),
    sa.Column('virtualExperience_14', sa.String(), nullable=True),
    sa.Column('underservedExperience_15', sa.String(), nullable=True),
    sa.Column('underservedPlan_16', sa.String(), nullable=True),
    sa.Column('federalGrantExperience_17', sa.String(), nullable=True),
    sa.Column('collaborationExperience_18', sa.String(), nullable=True),
    sa.Column('uniqueResorces_19', sa.String(), nullable=True),
    sa.Column('workplanDeliverables_20', sa.String(), nullable=True),
    sa.Column('milestoneTimelines_21', sa.String(), nullable=True),
    sa.Column('keyMetrics_22', sa.String(), nullable=True),
    sa.Column('shortTermCommitment_24', sa.Enum('Yes', 'No', name='short_term_commitment_enum'), nullable=False),
    sa.Column('longTermCommitment_25', sa.Enum('Yes', 'No', name='long_term_commitment_enum'), nullable=False),
    sa.Column('callRequest_26', sa.Enum('Yes', 'No', name='call_request_enum'), nullable=False),
    sa.Column('termsAndConditions_27', sa.Boolean(), nullable=False),
    sa.Column('user_timezone_30', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('desired_role_23',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('admin_lead', sa.Boolean(), nullable=True),
    sa.Column('admin_support', sa.Boolean(), nullable=True),
    sa.Column('regional_partner_lead', sa.Boolean(), nullable=True),
    sa.Column('regional_partner_support', sa.Boolean(), nullable=True),
    sa.Column('advisory_support', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eecbg_activities_10',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('category_1_strategy_development', sa.Boolean(), nullable=True),
    sa.Column('category_2_retaining_consulting', sa.Boolean(), nullable=True),
    sa.Column('category_3_residential_audits', sa.Boolean(), nullable=True),
    sa.Column('category_4_financial_incentives', sa.Boolean(), nullable=True),
    sa.Column('category_5_retrofit_grants', sa.Boolean(), nullable=True),
    sa.Column('category_6_efficiency_programs', sa.Boolean(), nullable=True),
    sa.Column('category_7_transportation_energy', sa.Boolean(), nullable=True),
    sa.Column('category_8_building_codes', sa.Boolean(), nullable=True),
    sa.Column('category_9_energy_distribution', sa.Boolean(), nullable=True),
    sa.Column('category_10_material_conservation', sa.Boolean(), nullable=True),
    sa.Column('category_11_landfill_gas', sa.Boolean(), nullable=True),
    sa.Column('category_12_traffic_signals', sa.Boolean(), nullable=True),
    sa.Column('category_13_renewable_energy', sa.Boolean(), nullable=True),
    sa.Column('category_14_private_sector_funding', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('global_area', sa.Boolean(), nullable=True),
    sa.Column('national', sa.Boolean(), nullable=True),
    sa.Column('alabama', sa.Boolean(), nullable=True),
    sa.Column('alaska', sa.Boolean(), nullable=True),
    sa.Column('arizona', sa.Boolean(), nullable=True),
    sa.Column('arkansas', sa.Boolean(), nullable=True),
    sa.Column('california', sa.Boolean(), nullable=True),
    sa.Column('colorado', sa.Boolean(), nullable=True),
    sa.Column('connecticut', sa.Boolean(), nullable=True),
    sa.Column('delaware', sa.Boolean(), nullable=True),
    sa.Column('district_of_columbia', sa.Boolean(), nullable=True),
    sa.Column('florida', sa.Boolean(), nullable=True),
    sa.Column('georgia', sa.Boolean(), nullable=True),
    sa.Column('hawaii', sa.Boolean(), nullable=True),
    sa.Column('idaho', sa.Boolean(), nullable=True),
    sa.Column('illinois', sa.Boolean(), nullable=True),
    sa.Column('indiana', sa.Boolean(), nullable=True),
    sa.Column('iowa', sa.Boolean(), nullable=True),
    sa.Column('kansas', sa.Boolean(), nullable=True),
    sa.Column('kentucky', sa.Boolean(), nullable=True),
    sa.Column('louisiana', sa.Boolean(), nullable=True),
    sa.Column('maine', sa.Boolean(), nullable=True),
    sa.Column('maryland', sa.Boolean(), nullable=True),
    sa.Column('massachusetts', sa.Boolean(), nullable=True),
    sa.Column('michigan', sa.Boolean(), nullable=True),
    sa.Column('minnesota', sa.Boolean(), nullable=True),
    sa.Column('mississippi', sa.Boolean(), nullable=True),
    sa.Column('missouri', sa.Boolean(), nullable=True),
    sa.Column('montana', sa.Boolean(), nullable=True),
    sa.Column('nebraska', sa.Boolean(), nullable=True),
    sa.Column('nevada', sa.Boolean(), nullable=True),
    sa.Column('new_hampshire', sa.Boolean(), nullable=True),
    sa.Column('new_jersey', sa.Boolean(), nullable=True),
    sa.Column('new_mexico', sa.Boolean(), nullable=True),
    sa.Column('new_york', sa.Boolean(), nullable=True),
    sa.Column('north_carolina', sa.Boolean(), nullable=True),
    sa.Column('north_dakota', sa.Boolean(), nullable=True),
    sa.Column('ohio', sa.Boolean(), nullable=True),
    sa.Column('oklahoma', sa.Boolean(), nullable=True),
    sa.Column('oregon', sa.Boolean(), nullable=True),
    sa.Column('pennsylvania', sa.Boolean(), nullable=True),
    sa.Column('rhode_island', sa.Boolean(), nullable=True),
    sa.Column('south_carolina', sa.Boolean(), nullable=True),
    sa.Column('south_dakota', sa.Boolean(), nullable=True),
    sa.Column('tennessee', sa.Boolean(), nullable=True),
    sa.Column('texas', sa.Boolean(), nullable=True),
    sa.Column('utah', sa.Boolean(), nullable=True),
    sa.Column('vermont', sa.Boolean(), nullable=True),
    sa.Column('virginia', sa.Boolean(), nullable=True),
    sa.Column('washington', sa.Boolean(), nullable=True),
    sa.Column('west_virginia', sa.Boolean(), nullable=True),
    sa.Column('wisconsin', sa.Boolean(), nullable=True),
    sa.Column('wyoming', sa.Boolean(), nullable=True),
    sa.Column('american_samoa', sa.Boolean(), nullable=True),
    sa.Column('guam', sa.Boolean(), nullable=True),
    sa.Column('northern_mariana_islands', sa.Boolean(), nullable=True),
    sa.Column('puerto_rico', sa.Boolean(), nullable=True),
    sa.Column('us_virgin_islands', sa.Boolean(), nullable=True),
    sa.Column('federally_recognized_tribes', sa.Boolean(), nullable=True),
    sa.Column('alaska_native_villages', sa.Boolean(), nullable=True),
    sa.Column('energy_communities', sa.Boolean(), nullable=True),
    sa.Column('disadvantaged_communities', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=40), nullable=False))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    op.drop_table('service_areas')
    op.drop_table('eecbg_activities_10')
    op.drop_table('desired_role_23')
    op.drop_table('forms')
    # ### end Alembic commands ###
